# Generated by Django 4.0.4 on 2022-05-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_alter_house_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['name'], 'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
    ]
